
CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)     UNIQUE                 NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

create table if not exists locations
(
        id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
        lat float  NOT NULL,
        lon float   NOT NULL
);
create table if not exists categories
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name         varchar(1024) UNIQUE NOT NULL
);
create table if not exists events (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
        annotation varchar(2048),
        category_id integer references  categories(id),
        created_On TIMESTAMP WITHOUT TIME ZONE,
        description VARCHAR(128000),
        event_Date TIMESTAMP WITHOUT TIME ZONE,
        initiator_id integer references users(id),
        location integer references locations(id),
        paid boolean,
        PARTICIPANT_LIMIT integer,
        PUBLISHED_ON TIMESTAMP WITHOUT TIME ZONE,
        REQUEST_MODERATION boolean,
        state varchar(64),
        title varchar(1024)
);
create table if not exists requests
(
    id  bigint generated by default as identity PRIMARY KEY not null,
    created TIMESTAMP WITHOUT TIME ZONE,
    event_id integer references events(id),
    requester_id integer references users(id),
    status varchar(64)
);
create table if not exists compilations
(
    id bigint generated by default as identity PRIMARY KEY not null,
    title varchar(1024),
    pinned boolean
);
create table if not exists compilation_events
(
    id bigint references compilations(id),
    event_id bigint references events(id),
    CONSTRAINT compilation PRIMARY KEY (id,event_id)
);


